export { ReactComponent as BookMarkIcon } from "./icon-bookmark.svg"
export { ReactComponent as CheckIcon } from "./icon-check.svg"
export { ReactComponent as CloseMenuIcon } from "./icon-close-menu.svg"
export { ReactComponent as CloseModalIcon } from "./icon-close-modal.svg"
export { ReactComponent as BurgerIcon } from "./icon-hamburger.svg"
export { ReactComponent as ComanyLogo } from "./icon-logo-mastercraft.svg"
export { ReactComponent as LogoIcon } from "./icon-logo.svg"